/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.util.Iterator;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Asus
 */
public class mainmenu extends javax.swing.JFrame {
    Connection conn =null;
    PreparedStatement ps=null;
    ResultSet rs =null;
    
    int mouseX,mouseY;
    String status;
            
            
    public mainmenu() {
        initComponents();
        conn = MyConnection.getConnection();
    }
    
    public mainmenu(String empName,String EmpDesignation) {
        initComponents();
        lblEmpName.setText(empName.toUpperCase());
        lblEmpDesignation.setText(EmpDesignation); 
                
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        headerpanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        sidepanel = new javax.swing.JPanel();
        sidepanel1 = new javax.swing.JPanel();
        btn2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblEmpName = new javax.swing.JLabel();
        lblEmpDesignation = new javax.swing.JLabel();
        btn1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        centrepanel = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        employeereport = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        addemployee = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        updateemployee = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        deleteemployee = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        calculatesalary = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        updatesalary = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        generatesalary = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        deleteemployee1 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        p1_add = new javax.swing.JPanel();
        backbutton = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        srno = new javax.swing.JTextField();
        txtFullname = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel63 = new javax.swing.JLabel();
        txtnumber = new javax.swing.JTextField();
        txtsalary = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        HEADER = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtaddress = new javax.swing.JTextField();
        txtdepartment = new javax.swing.JComboBox<>();
        txtdesignation = new javax.swing.JComboBox<>();
        p1_update = new javax.swing.JPanel();
        backbutton1 = new javax.swing.JButton();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        txtFullname1 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel71 = new javax.swing.JLabel();
        txtdepartment1 = new javax.swing.JTextField();
        txtaddress1 = new javax.swing.JTextField();
        HEADER1 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel74 = new javax.swing.JLabel();
        txtdesignation1 = new javax.swing.JTextField();
        txtnumber3 = new javax.swing.JTextField();
        p2 = new javax.swing.JPanel();
        p3 = new javax.swing.JPanel();
        p1_delete = new javax.swing.JPanel();
        backbutton2 = new javax.swing.JButton();
        jLabel72 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        txtsearch1 = new javax.swing.JTextField();
        txtFullname2 = new javax.swing.JTextField();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel79 = new javax.swing.JLabel();
        txtdepartment2 = new javax.swing.JTextField();
        txtaddress2 = new javax.swing.JTextField();
        HEADER2 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        bttndelete = new javax.swing.JButton();
        jLabel81 = new javax.swing.JLabel();
        txtdesignation2 = new javax.swing.JTextField();
        txtnumber4 = new javax.swing.JTextField();
        p5 = new javax.swing.JPanel();
        p4 = new javax.swing.JPanel();

        jPanel2.setBackground(new java.awt.Color(218, 228, 230));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerpanel.setBackground(new java.awt.Color(255, 255, 255));
        headerpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Cancel_Icon.png"))); // NOI18N
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        headerpanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, -1, -1));

        getContentPane().add(headerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 770, 35));

        sidepanel.setBackground(new java.awt.Color(0, 0, 104));
        sidepanel.setPreferredSize(new java.awt.Dimension(130, 600));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel1.setBackground(new java.awt.Color(0, 0, 104));
        sidepanel1.setPreferredSize(new java.awt.Dimension(130, 600));
        sidepanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn2.setBackground(new java.awt.Color(0, 0, 51));
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Employee");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Employee_Icon.png"))); // NOI18N

        javax.swing.GroupLayout btn2Layout = new javax.swing.GroupLayout(btn2);
        btn2.setLayout(btn2Layout);
        btn2Layout.setHorizontalGroup(
            btn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn2Layout.setVerticalGroup(
            btn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel16)
                .addGap(0, 0, 0)
                .addComponent(jLabel5))
        );

        sidepanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 60));

        btn3.setBackground(new java.awt.Color(0, 0, 51));
        btn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Salary_Icon.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Salary");

        btn4.setBackground(new java.awt.Color(0, 0, 51));
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Salary_Icon.png"))); // NOI18N
        btn4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Salary");
        btn4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, 15));

        btn6.setBackground(new java.awt.Color(0, 0, 51));
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Salary_Icon.png"))); // NOI18N
        btn6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Salary");
        btn6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 130, 15));

        btn7.setBackground(new java.awt.Color(0, 0, 51));
        btn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Salary_Icon.png"))); // NOI18N
        btn7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Salary");
        btn7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, 15));

        btn6.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 130, 60));

        javax.swing.GroupLayout btn3Layout = new javax.swing.GroupLayout(btn3);
        btn3.setLayout(btn3Layout);
        btn3Layout.setHorizontalGroup(
            btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn3Layout.setVerticalGroup(
            btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(jLabel7)
                .addGap(25, 25, 25)
                .addGroup(btn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        sidepanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 130, 60));

        btn8.setBackground(new java.awt.Color(0, 0, 51));
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Leave");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Leave_Icon.png"))); // NOI18N

        javax.swing.GroupLayout btn8Layout = new javax.swing.GroupLayout(btn8);
        btn8.setLayout(btn8Layout);
        btn8Layout.setHorizontalGroup(
            btn8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn8Layout.setVerticalGroup(
            btn8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(jLabel17))
        );

        sidepanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 130, 60));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel3.setBackground(new java.awt.Color(0, 0, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Log Out");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidepanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 90, 30));

        sidepanel.add(sidepanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 140, 600));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\anjayyy\\User_Icon.png")); // NOI18N
        sidepanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 90));

        lblEmpName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmpName.setForeground(new java.awt.Color(255, 0, 0));
        lblEmpName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpName.setText("Empname");
        sidepanel.add(lblEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 130, 15));

        lblEmpDesignation.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblEmpDesignation.setForeground(new java.awt.Color(102, 204, 255));
        lblEmpDesignation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpDesignation.setText("EmpDesignation");
        sidepanel.add(lblEmpDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 130, 15));

        btn1.setBackground(new java.awt.Color(0, 0, 51));
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Laptop_Icon.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Dashboard");

        javax.swing.GroupLayout btn1Layout = new javax.swing.GroupLayout(btn1);
        btn1.setLayout(btn1Layout);
        btn1Layout.setHorizontalGroup(
            btn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn1Layout.setVerticalGroup(
            btn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(10, 10, 10)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepanel.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 130, 60));

        btn5.setBackground(new java.awt.Color(0, 0, 51));
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });
        btn5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("View Profil");
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(255, 255, 255)));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        btn5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 27));

        sidepanel.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 30));

        getContentPane().add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 610));

        centrepanel.setAlignmentX(0.0F);
        centrepanel.setAlignmentY(0.0F);
        centrepanel.setMinimumSize(new java.awt.Dimension(900, 450));
        centrepanel.setLayout(new java.awt.CardLayout());

        p1.setBackground(new java.awt.Color(212, 228, 230));
        p1.setMinimumSize(new java.awt.Dimension(900, 450));
        p1.setPreferredSize(new java.awt.Dimension(900, 450));
        p1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p1MouseClicked(evt);
            }
        });
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Employee Section");
        p1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Welcome To Emp System ");
        p1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));
        p1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 560, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Identicator_Icon.png"))); // NOI18N
        p1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        employeereport.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(104, 104, 104)));
        employeereport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeereport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 102));
        jLabel24.setText("Employee report");
        employeereport.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(104, 104, 104)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\anjayyy\\Add_Icon.png")); // NOI18N
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel26.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 255, 0));
        jLabel26.setText("ADD employee");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        employeereport.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, 120));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Report_Icon.png"))); // NOI18N
        employeereport.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        p1.add(employeereport, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 140, 120));

        addemployee.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(104, 104, 104)));
        addemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addemployeeMouseClicked(evt);
            }
        });
        addemployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\anjayyy\\Add_Icon.png")); // NOI18N
        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addemployee.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel28.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 255, 0));
        jLabel28.setText("ADD employee");
        addemployee.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(104, 104, 104)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\anjayyy\\Add_Icon.png")); // NOI18N
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel30.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 255, 0));
        jLabel30.setText("ADD employee");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        addemployee.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, 120));

        p1.add(addemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, 120));

        updateemployee.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(104, 104, 104)));
        updateemployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateemployeeMouseClicked(evt);
            }
        });
        updateemployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Update_Icon.png"))); // NOI18N
        updateemployee.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel32.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 51, 102));
        jLabel32.setText("Update Employee");
        updateemployee.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(104, 104, 104)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\anjayyy\\Add_Icon.png")); // NOI18N
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel34.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 255, 0));
        jLabel34.setText("ADD employee");
        jPanel9.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        updateemployee.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, 120));

        p1.add(updateemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 140, 120));

        deleteemployee.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(104, 104, 104)));
        deleteemployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteemployeeMouseClicked(evt);
            }
        });
        deleteemployee.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Delete_Icon.png"))); // NOI18N
        deleteemployee.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel37.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 0, 0));
        jLabel37.setText("Delete Employee");
        deleteemployee.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(104, 104, 104)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\anjayyy\\Add_Icon.png")); // NOI18N
        jPanel11.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel39.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 255, 0));
        jLabel39.setText("ADD employee");
        jPanel11.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        deleteemployee.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, 120));

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\anjayyy\\Add_Icon.png")); // NOI18N
        deleteemployee.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        p1.add(deleteemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 140, 120));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setText("Salary Section");
        p1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Identicator_Icon.png"))); // NOI18N
        p1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        calculatesalary.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(104, 104, 104)));
        calculatesalary.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 102, 102));
        jLabel42.setText("Calculate Salary");
        calculatesalary.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(104, 104, 104)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\anjayyy\\Add_Icon.png")); // NOI18N
        jPanel6.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel44.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 255, 0));
        jLabel44.setText("ADD employee");
        jPanel6.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        calculatesalary.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, 120));

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Calculate_Salary_Icon.png"))); // NOI18N
        calculatesalary.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        p1.add(calculatesalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 140, 120));

        updatesalary.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(104, 104, 104)));
        updatesalary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatesalary.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Update_Salary_Icon.png"))); // NOI18N
        updatesalary.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel47.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 51, 51));
        jLabel47.setText("Update Salary");
        updatesalary.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(104, 104, 104)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\anjayyy\\Add_Icon.png")); // NOI18N
        jPanel8.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel49.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 255, 0));
        jLabel49.setText("ADD employee");
        jPanel8.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        updatesalary.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, 120));

        p1.add(updatesalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 140, 120));

        generatesalary.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(104, 104, 104)));
        generatesalary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generatesalary.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Generate_Salary_Icon.png"))); // NOI18N
        generatesalary.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel51.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 204, 0));
        jLabel51.setText("Generate Salary");
        generatesalary.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(104, 104, 104)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\anjayyy\\Add_Icon.png")); // NOI18N
        jPanel10.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel53.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 255, 0));
        jLabel53.setText("ADD employee");
        jPanel10.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        generatesalary.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, 120));

        p1.add(generatesalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 140, 120));

        deleteemployee1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(104, 104, 104)));
        deleteemployee1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteemployee1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Salary_Receipt_Icon.png"))); // NOI18N
        deleteemployee1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel55.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 153, 153));
        jLabel55.setText("Generate Receipt");
        deleteemployee1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 3, new java.awt.Color(104, 104, 104)));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\anjayyy\\Add_Icon.png")); // NOI18N
        jPanel12.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel57.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 255, 0));
        jLabel57.setText("ADD employee");
        jPanel12.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        deleteemployee1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, 120));

        p1.add(deleteemployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 140, 120));

        centrepanel.add(p1, "card2");

        p1_add.setBackground(new java.awt.Color(102, 204, 255));
        p1_add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backbutton.setBackground(new java.awt.Color(255, 0, 51));
        backbutton.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        backbutton.setForeground(new java.awt.Color(255, 255, 255));
        backbutton.setText("Go Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        p1_add.add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 120, 40));

        jLabel62.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel62.setText("Department:");
        p1_add.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel58.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel58.setText("Designation:");
        p1_add.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        jLabel61.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel61.setText("Status:");
        p1_add.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        jLabel59.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel59.setText("Sr No:");
        p1_add.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jLabel64.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel64.setText("Full Name:");
        p1_add.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        srno.setForeground(new java.awt.Color(204, 204, 204));
        srno.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        srno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                srnoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                srnoFocusLost(evt);
            }
        });
        p1_add.add(srno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 560, 20));

        txtFullname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtFullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullnameActionPerformed(evt);
            }
        });
        p1_add.add(txtFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 560, 20));

        jRadioButton1.setText("In-Active");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        p1_add.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, -1));

        jRadioButton2.setText("Active");
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        p1_add.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        jLabel63.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel63.setText("Contact no:");
        p1_add.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));
        p1_add.add(txtnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 260, 30));

        txtsalary.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        p1_add.add(txtsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 560, 30));

        jLabel60.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel60.setText("Salary");
        p1_add.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        HEADER.setBackground(new java.awt.Color(0, 0, 154));
        HEADER.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 154));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("add employee:");
        HEADER.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 960, 30));

        p1_add.add(HEADER, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 50));

        jLabel65.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel65.setText("Address:");
        p1_add.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ADD EMPLOYEE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        p1_add.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 180, 40));

        txtaddress.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        p1_add.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 560, 30));

        txtdepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "Account", "Manifacturing", "packing", "Sales" }));
        txtdepartment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtdepartmentItemStateChanged(evt);
            }
        });
        p1_add.add(txtdepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, -1));

        txtdesignation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Designation" }));
        p1_add.add(txtdesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 280, -1));

        centrepanel.add(p1_add, "card3");

        p1_update.setBackground(new java.awt.Color(153, 204, 255));
        p1_update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backbutton1.setBackground(new java.awt.Color(255, 0, 51));
        backbutton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        backbutton1.setForeground(new java.awt.Color(255, 255, 255));
        backbutton1.setText("Go Back");
        backbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutton1ActionPerformed(evt);
            }
        });
        p1_update.add(backbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 120, 40));

        jLabel66.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel66.setText("Department:");
        p1_update.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel67.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel67.setText("Designation:");
        p1_update.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        jLabel68.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel68.setText("Status:");
        p1_update.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        jLabel69.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel69.setText("Sr No:");
        p1_update.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jLabel70.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel70.setText("Full Name:");
        p1_update.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        txtsearch.setForeground(new java.awt.Color(204, 204, 204));
        txtsearch.setText("                                                                              Enter id to search");
        txtsearch.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtsearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsearchFocusLost(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchKeyPressed(evt);
            }
        });
        p1_update.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 560, 20));

        txtFullname1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtFullname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullname1ActionPerformed(evt);
            }
        });
        p1_update.add(txtFullname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 560, 20));

        jRadioButton3.setText("In-Active");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        p1_update.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, -1));

        jRadioButton4.setText("Active");
        jRadioButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton4ItemStateChanged(evt);
            }
        });
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        p1_update.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        jLabel71.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel71.setText("Contact no:");
        p1_update.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));
        p1_update.add(txtdepartment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, 30));

        txtaddress1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        p1_update.add(txtaddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 560, 30));

        HEADER1.setBackground(new java.awt.Color(0, 0, 154));
        HEADER1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel73.setBackground(new java.awt.Color(0, 0, 154));
        jLabel73.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("update employee");
        HEADER1.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 960, 30));

        p1_update.add(HEADER1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 50));

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update Employee");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        p1_update.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 180, 40));

        jLabel74.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel74.setText("Address:");
        p1_update.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));
        p1_update.add(txtdesignation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 280, 30));
        p1_update.add(txtnumber3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 260, 30));

        centrepanel.add(p1_update, "card3");

        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        centrepanel.add(p2, "card3");

        p3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        centrepanel.add(p3, "card5");

        p1_delete.setBackground(new java.awt.Color(153, 204, 255));
        p1_delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backbutton2.setBackground(new java.awt.Color(255, 0, 51));
        backbutton2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        backbutton2.setForeground(new java.awt.Color(255, 255, 255));
        backbutton2.setText("Go Back");
        backbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutton2ActionPerformed(evt);
            }
        });
        p1_delete.add(backbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 120, 40));

        jLabel72.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel72.setText("Department:");
        p1_delete.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLabel75.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel75.setText("Designation:");
        p1_delete.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        jLabel76.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel76.setText("Status:");
        p1_delete.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        jLabel77.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel77.setText("Sr No:");
        p1_delete.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jLabel78.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel78.setText("Full Name:");
        p1_delete.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        txtsearch1.setForeground(new java.awt.Color(204, 204, 204));
        txtsearch1.setText("                                                                              Enter id to search");
        txtsearch1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtsearch1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsearch1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsearch1FocusLost(evt);
            }
        });
        txtsearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearch1KeyPressed(evt);
            }
        });
        p1_delete.add(txtsearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 560, 20));

        txtFullname2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtFullname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullname2ActionPerformed(evt);
            }
        });
        p1_delete.add(txtFullname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 560, 20));

        jRadioButton5.setText("In-Active");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        p1_delete.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, -1));

        jRadioButton6.setText("Active");
        jRadioButton6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton6ItemStateChanged(evt);
            }
        });
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        p1_delete.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        jLabel79.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel79.setText("Contact no:");
        p1_delete.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));
        p1_delete.add(txtdepartment2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, 30));

        txtaddress2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        p1_delete.add(txtaddress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 560, 30));

        HEADER2.setBackground(new java.awt.Color(0, 0, 154));
        HEADER2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel80.setBackground(new java.awt.Color(0, 0, 154));
        jLabel80.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Delete Employee");
        HEADER2.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 960, 30));

        p1_delete.add(HEADER2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 50));

        bttndelete.setBackground(new java.awt.Color(0, 0, 102));
        bttndelete.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        bttndelete.setForeground(new java.awt.Color(255, 255, 255));
        bttndelete.setText("Delete");
        bttndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttndeleteActionPerformed(evt);
            }
        });
        p1_delete.add(bttndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 180, 40));

        jLabel81.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel81.setText("Address:");
        p1_delete.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));
        p1_delete.add(txtdesignation2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 280, 30));
        p1_delete.add(txtnumber4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 260, 30));

        centrepanel.add(p1_delete, "card3");

        p5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        centrepanel.add(p5, "card6");

        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        centrepanel.add(p4, "card4");

        getContentPane().add(centrepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 770, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void onClick (JPanel panel){
    panel.setBackground(new Color(0,153,204));
}
    private void onLeaveClick (JPanel panel){
    panel.setBackground(new Color(0,0,51));
    }
    
    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
       onLeaveClick(btn2);
        onClick(btn1);
        onLeaveClick(btn3);
        onLeaveClick(btn4);
        onLeaveClick(btn5);
        onLeaveClick(btn8);
        
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
    }//GEN-LAST:event_btn1MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        // TODO add your handling code here:
        onClick(btn2);
        onLeaveClick(btn1);
        onLeaveClick(btn3);
        onLeaveClick(btn4);
        onLeaveClick(btn5);
        onLeaveClick(btn8);
        
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        // TODO add your handling code here:
        onLeaveClick(btn2);
        onLeaveClick(btn1);
        onClick(btn3);
        onLeaveClick(btn4);
        onLeaveClick(btn5);
        onLeaveClick(btn8);
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
        p5.setVisible(false);
    }//GEN-LAST:event_btn3MouseClicked

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        onLeaveClick(btn2);
        onLeaveClick(btn1);
        onLeaveClick(btn3);
        onLeaveClick(btn4);
        onLeaveClick(btn5);
        onClick(btn8);
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        p5.setVisible(false);
    }//GEN-LAST:event_btn8MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
      Login l= new Login(); 
       l.setVisible(true);
       this.dispose();
       
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        onLeaveClick(btn2);
        onLeaveClick(btn1);
        onLeaveClick(btn3);
        onLeaveClick(btn4);
        onClick(btn5);
        onLeaveClick(btn8);

        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(true);
    }//GEN-LAST:event_btn5MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        onLeaveClick(btn2);
        onLeaveClick(btn1);
        onLeaveClick(btn3);
        onLeaveClick(btn4);
        onLeaveClick(btn5);
        onLeaveClick(btn8);
        
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(true);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
    status="Active";
    jRadioButton2.setSelected(true);
    jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        p1_add.setVisible(false);
        p1_update.setVisible(false);
        p1.setVisible(true );
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      int x = JOptionPane.showConfirmDialog(null,"Are you sure want to add this record?","Add record",JOptionPane.YES_NO_OPTION);
      if (x==0){
          try{
          String sql ="INSERT INTO `employe_list`(`fullname`, `department`, `designation`, `number`, `status`, `address`, `salary`) VALUES(?,?,?,?,?,?,?)";
          ps = conn.prepareStatement(sql);
          
          
          ps.setString(1,txtFullname.getText());
          ps.setString(2,(String)txtdepartment.getSelectedItem());
          ps.setString(3,(String)txtdesignation.getSelectedItem());
          ps.setString(4,txtnumber.getText());
          ps.setString(5, status);
          ps.setString(6,txtaddress.getText());
          ps.setString(7,txtsalary.getText());
          
          ps.execute();
          JOptionPane.showMessageDialog(null,"Data stored succesfully");
          
      }catch (Exception ex) {
          JOptionPane.showMessageDialog(null,ex);
      }
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ItemStateChanged


    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
status="In-Active";
    jRadioButton2.setSelected(false);
    jRadioButton1.setSelected(true);        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void p1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseClicked
        
    }//GEN-LAST:event_p1MouseClicked

    private void addemployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addemployeeMouseClicked
     p1_add.setVisible(true);
     p1.setVisible(false);
     p2.setVisible(false);
     p3.setVisible(false);
     p4.setVisible(false);
     p5.setVisible(false);
     
    }//GEN-LAST:event_addemployeeMouseClicked

    private void txtFullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullnameActionPerformed

    private void backbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutton1ActionPerformed
        p1_add.setVisible(false);
        p1_update.setVisible(false);
        p1.setVisible(true );
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);       
    }//GEN-LAST:event_backbutton1ActionPerformed

    private void txtFullname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullname1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton4ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ItemStateChanged

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String value1 = txtsearch.getText();
        String value2 = txtFullname1.getText();
        String value3 = txtdepartment1.getText();
        String value4 = txtdesignation1.getText();
        String value5 = txtnumber3.getText();
        String value6 = status;
        String value7 = txtaddress1.getText();
        
        
        int p= JOptionPane.showConfirmDialog(null,"Are you sure to update this record?","Update Record",JOptionPane.YES_NO_OPTION); 
        if (p==0) {
            try {
                String sql="UPDATE `employe_list` SET `srno`='"+value1+"',`fullname`='"+value2+"',`department`='"+value3+"',`designation`='"+value4+"',`number`='"+value5+"',`status`='"+value6+"',`address`='"+value7+"' WHERE `srno`='"+value1+"'";
                ps = conn.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Data updated successfully");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void srnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_srnoFocusGained
        
    }//GEN-LAST:event_srnoFocusGained

    private void srnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_srnoFocusLost
       
    }//GEN-LAST:event_srnoFocusLost

    private void txtsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyPressed
    if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
        
        try {
            String sql="Select * from employe_list where srno=?";
            ps = conn.prepareStatement(sql);
            ps.setString(1,txtsearch.getText());
            rs = ps.executeQuery();
            if (rs.next()) {
                txtFullname1.setText(rs.getString(2));
                txtdepartment1.setText(rs.getString(3));
                txtdesignation1.setText(rs.getString(4));
                txtnumber3.setText(rs.getString(5));
                if (rs.getString(6).equals("Active")) {
                    jRadioButton4.setSelected(true);
                    jRadioButton3.setSelected(false);  
                }else if (rs.getString(6 ).equals("In-Active")){
                    jRadioButton4.setSelected(false);
                    jRadioButton3.setSelected(true);
                }
                txtaddress1.setText(rs.getString(7));
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(mainmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    }//GEN-LAST:event_txtsearchKeyPressed

    private void updateemployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateemployeeMouseClicked
   p1.setVisible(false);
   p1_add.setVisible(false);
   p1_update.setVisible(true);
   p2.setVisible(false);
   p3.setVisible(false);
   p4.setVisible(false);
   p5.setVisible(false);
    }//GEN-LAST:event_updateemployeeMouseClicked

    @SuppressWarnings("empty-statement")
    private void txtdepartmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtdepartmentItemStateChanged
        ArrayList<String> array = new ArrayList<>();
        Iterator<String> iterator;
        if(txtdepartment.getSelectedItem().equals("Account")) {
            array.add("Charted Accountant");
            array.add("Head Accountant");
            array.add("Senior Accountant");
            array.add("Junior Accountant");
            iterator = array.iterator();
            while (iterator.hasNext()) {
            txtdesignation.addItem(iterator.next());
            }
        }else if (txtdepartment.getSelectedItem().equals("Manifacturing")) {
            array.add("Head Officer");
            array.add("Checker ");
            array.add("Superviser");
            array.add("Helper");
            iterator = array.iterator();
            while (iterator.hasNext()){
            txtdesignation.addItem(iterator.next());
        }
        }else if (txtdepartment.getSelectedItem().equals("Packing")) {
            array.add("Head packing Officer");
            array.add("Assembler ");
            array.add("Superviser");
            array.add("Helper");
            iterator = array.iterator();
            while (iterator.hasNext()){
            txtdesignation.addItem(iterator.next());
        }
        }else if (txtdepartment.getSelectedItem().equals("sales")) {
            array.add("Head sales Officer");
            array.add("quality man ");
            array.add("dispatcher");
            array.add("Helper");
            iterator = array.iterator();
            while (iterator.hasNext()){
            txtdesignation.addItem(iterator.next());
        }
        }
    
    }//GEN-LAST:event_txtdepartmentItemStateChanged

    private void txtsearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsearchFocusGained
     if(txtsearch.getText().trim().equals("Enter id to search")) {
            txtsearch.setText("");
            txtsearch.setForeground(new Color(153,153,153));
            
        }
        txtsearch.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtsearchFocusGained

    private void txtsearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsearchFocusLost
if(txtsearch.getText().trim().equals("")) {
           txtsearch.setText("                                                                              Enter id to search");
           txtFullname1.setText("");
           txtdepartment1.setText("");
           txtdesignation1.setText("");
           txtdepartment1.setText("");
           jRadioButton4.setSelected(false);
           jRadioButton3.setSelected(false);
           txtaddress1.setText("");
       }     
    }//GEN-LAST:event_txtsearchFocusLost

    private void backbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backbutton2ActionPerformed

    private void txtsearch1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsearch1FocusGained
        if (txtsearch1.getText().trim().equals("Enter id to search")){
            txtsearch1.setText("");
            txtsearch1.setForeground(new Color(153,153,153));
        }
        txtsearch1.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtsearch1FocusGained

    private void txtsearch1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsearch1FocusLost
       if (txtsearch1.getText().trim().equals("")){
           txtsearch1.setText("                                                                              Enter id to search");
           txtFullname2.setText("");
           txtdepartment2.setText("");
           txtdesignation2.setText("");
           txtnumber4.setText("");
           jRadioButton6.setSelected(false);
           jRadioButton5.setSelected(false);
           txtaddress2.setText("");
       }
       txtsearch1.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_txtsearch1FocusLost

    private void txtsearch1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearch1KeyPressed
       if (evt.getKeyCode()==KeyEvent.VK_ENTER){
           try {
               String sql ="select*from employe_list where srno=?";
               ps= conn.prepareStatement(sql);
               ps.setString(1, txtsearch1.getText());
               rs = ps.executeQuery();
               if (rs.next()) {
                   txtFullname2.setText(rs.getString(2));
                   txtdepartment2.setText(rs.getString(3));
                   txtdesignation2.setText(rs.getString(4));
                   txtnumber4.setText(rs.getString(5));
                   if(rs.getString(7).equals("Active")){
                       jRadioButton6.setSelected(true);
                       jRadioButton5.setSelected(false);
                   }else if (rs.getString(7).equals("In-Active")){
                       jRadioButton6.setSelected(false);
                       jRadioButton5.setSelected(true);
                   }
                   txtaddress2.setText(rs.getString(8));
               
                           
               }
           } catch (SQLException ex) {
               Logger.getLogger(mainmenu.class.getName()).log(Level.SEVERE, null, ex);
           }
            
       }
    }//GEN-LAST:event_txtsearch1KeyPressed

    private void txtFullname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullname2ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton6ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ItemStateChanged

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void bttndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttndeleteActionPerformed
        int p= JOptionPane.showConfirmDialog(null,"Are you sure to delete this record from database?","Delete Record",JOptionPane.YES_NO_OPTION );
       if(p==0) {
            try {
                String sql = "delete from employe_list where srno=?";
                ps = conn.prepareStatement(sql);
                ps.setString(1,txtsearch1.getText());
                ps.execute();
                JOptionPane.showMessageDialog(null,"Data delete succesfully");
                
                txtsearch1.setText("                                                                              Enter id to search");
           txtFullname2.setText("");
           txtdepartment2.setText("");
           txtdesignation2.setText("");
           txtnumber4.setText("");
           jRadioButton6.setSelected(false);
           jRadioButton5.setSelected(false);
           txtaddress2.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
       }
        
    }//GEN-LAST:event_bttndeleteActionPerformed

    private void deleteemployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteemployeeMouseClicked
        // TODO add your handling code here:
        p1_delete.setVisible(true);
        p1_add.setVisible(false);
        p1_update.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
    }//GEN-LAST:event_deleteemployeeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       //</editor-fold>
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mainmenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HEADER;
    private javax.swing.JPanel HEADER1;
    private javax.swing.JPanel HEADER2;
    private javax.swing.JPanel addemployee;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton backbutton1;
    private javax.swing.JButton backbutton2;
    private javax.swing.JPanel btn1;
    private javax.swing.JPanel btn2;
    private javax.swing.JPanel btn3;
    private javax.swing.JPanel btn4;
    private javax.swing.JPanel btn5;
    private javax.swing.JPanel btn6;
    private javax.swing.JPanel btn7;
    private javax.swing.JPanel btn8;
    private javax.swing.JButton bttndelete;
    private javax.swing.JPanel calculatesalary;
    private javax.swing.JPanel centrepanel;
    private javax.swing.JPanel deleteemployee;
    private javax.swing.JPanel deleteemployee1;
    private javax.swing.JPanel employeereport;
    private javax.swing.JPanel generatesalary;
    private javax.swing.JPanel headerpanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEmpDesignation;
    private javax.swing.JLabel lblEmpName;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p1_add;
    private javax.swing.JPanel p1_delete;
    private javax.swing.JPanel p1_update;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel sidepanel1;
    private javax.swing.JTextField srno;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtFullname1;
    private javax.swing.JTextField txtFullname2;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtaddress1;
    private javax.swing.JTextField txtaddress2;
    private javax.swing.JComboBox<String> txtdepartment;
    private javax.swing.JTextField txtdepartment1;
    private javax.swing.JTextField txtdepartment2;
    private javax.swing.JComboBox<String> txtdesignation;
    private javax.swing.JTextField txtdesignation1;
    private javax.swing.JTextField txtdesignation2;
    private javax.swing.JTextField txtnumber;
    private javax.swing.JTextField txtnumber3;
    private javax.swing.JTextField txtnumber4;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtsearch1;
    private javax.swing.JPanel updateemployee;
    private javax.swing.JPanel updatesalary;
    // End of variables declaration//GEN-END:variables

    private void onClick(JLabel jLabel19) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
